### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by fladson** [smeikx/kitty-color-control#1]
Hey @smeikx 
Thank you for creating this, it is a feature that I miss a lot from Alacritty.
I was thinking of doing it for myself but never found a nice way to do it.
I installed the plugin but I don't see it working, is there a way to debug it?

This is what I have in the `init.vim`.
```
let g:kitty_address = 'unix:/tmp/mykitty-$KITTY_PID'
set guicursor=n-v-c:block-Cursor/lCursor,i-ci-ve:ver25-Cursor/lCursor,r-cr:hor20,o:hor50
```

I've also tried with `let g:kitty_address = 'unix:/tmp/mykitty'`

This is what I have in my `kitty.conf`
```
allow_remote_control yes
listen_on unix:/tmp/mykitty
```

I am running on macos and have `sed`, `grep` and `tr` installed. Is there an easy way to debug it?

**Comment by smeikx** [comment]
Thanks for the advice!

I’ll be experimenting with escape codes (first have to figure out how to use them) and hopefully get this thing working properly on macOS in the process.

**Comment by kovidgoyal** [comment]
For colors, see https://sw.kovidgoyal.net/kitty/faq/#how-do-i-change-the-colors-in-a-running-kitty-instance  it documents the needed escape codes.

**Comment by smeikx** [comment]
Created an issue for this: #2
